# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Reficul
subtitle:
description:
author: Reficul
email: xuzhenglun@gmail.com
language: zh-CN

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://reficul.io
enforce_ssl: reficul.io
root: /
permalink: :year/:month/:day/:title/
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
permalink_defaults:

# Directory
source_dir: source
public_dir: public

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
highlight:
  enable: true
  line_number: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Archives
## 2: Enable pagination
## 1: Disable pagination
## 0: Fully Disable
#archive: 2
#category: 2
#tag: 2

# Server
## Hexo uses Connect as a server
## You can customize the logger format as defined in
## http://www.senchalabs.org/connect/logger.html
port: 4000
server_ip: 0.0.0.0
logger: false
logger_format: dev

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: MMM D YYYY
time_format: H:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Disqus
disqus_shortname: xuzhenglun

# Extensions
## Plugins: https://github.com/hexojs/hexo/wiki/Plugins
## Themes: https://github.com/hexojs/hexo/wiki/Themes
theme: next
exclude_generator:

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:xuzhenglun/xuzhenglun.github.io.git

  #jsonContent:
  #  meta: false
  #  pages: false
  #  posts:
  #    title: true
  #    date: true
  #    path: true
  #    text: false
  #    raw: false
  #    content: false
  #    slug: false
  #    updated: false
  #    comments: false
  #    link: false
  #    permalink: false
  #    excerpt: false
  #    categories: false
  #    tags: true
theme_config:
  avatar:
    url: /images/icon.jpg

  footer:
    since: 2015
    copyright: Reficul

  social:
    GitHub: https://github.com/xuzhenglun || github
    E-Mail: mailto:xuzhenglun@gmail.com || envelope
    Twitter: https://twitter.com/xuzhenglun || twitter

  social_icons:
    enable: true
    icons_only: false
    transition: false

  links:
    Eric: https://farer.org/
    Sakeven: https://sakeven.me
    realityOne: https://reality0ne.com
    JJY: https://justjjy.com
    Renlulu: https://renlulu.github.io
    Summer: https://g.yannxia.top
    TomWei: https://tomwei7.com
    TaoGe: https://yowenter.github.io
    Ylck: https://ylck.me
    Wangzhezhe: https://wangzhezhe.github.io/
    Clark: https://blog.jinwei.me
    Hypo: https://blog.ihypo.net

  sidebar:
    position: left
    display: hide

  symbols_count_time:
    separated_meta: true
    item_text_post: true
    item_text_total: true
    awl: 2
    wpm: 275

  creative_commons:
    license: by-nc-sa
    sidebar: false
    post: true
    language:

  graphviz:
    enable: true
  mermaid: true
  math:
    per_page: true
    mathjax:
      enable: true
      mhchem: false

  disqus:
    enable: true
    shortname: xuzhenglun
    count: false
    lazyload: true
    post_meta_order: 0

  google_analytics:
    tracking_id: UA-57211109-1
    localhost_ignored: true

  motion:
    enable: false

  three:
    enable: true
    canvas_lines: true

  adsense:
    enable: true
    id: ca-pub-2538407472813986
